AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  discord-bot-minecraft-ec2-serverless

  Sample SAM Template for discord-bot-minecraft-ec2-serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  InteractionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        Interaction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /interactions
            Method: post
      Environment:
        Variables:
          APPLICATION_PUBLIC_KEY: 'ac717bd98d442a772502bafe4daf5ae81cf80faa132a4ad180b8d914b29b4c28'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InteractionApi:
    Description: "API Gateway endpoint URL for Prod stage for Interaction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/interactions"
  InteractionFunction:
    Description: "Interaction Lambda Function ARN"
    Value: !GetAtt InteractionFunction.Arn
  InteractionFunctionIamRole:
    Description: "Implicit IAM Role created for Interaction function"
    Value: !GetAtt InteractionFunctionRole.Arn
